import { Condition } from "../cpu-state";
import { RegisterPair, Register } from "../regs";

import {
  addRegisterPair,
  addToStackPointer,
  decrementRegisterPair,
  incrementRegisterPair,
} from "./arithmetic16";
import {
  addImmediate,
  addImmediateWithCarry,
  addIndirectHL,
  addIndirectHLWithCarry,
  addRegister,
  addRegisterWithCarry,
  andImmediate,
  andIndirectHL,
  andRegister,
  compareImmediate,
  compareIndirectHL,
  compareRegister,
  complementAccumulator,
  complementCarryFlag,
  decimalAdjustAccumulator,
  decrementIndirectHL,
  decrementRegister,
  incrementIndirectHL,
  incrementRegister,
  orImmediate,
  orIndirectHL,
  orRegister,
  setCarryFlag,
  subtractImmediate,
  subtractImmediateWithCarry,
  subtractIndirectHL,
  subtractIndirectHLWithCarry,
  subtractRegister,
  subtractRegisterWithCarry,
  xorImmediate,
  xorIndirectHL,
  xorRegister,
} from "./arithmetic8";
import {
  rotateLeftAccumulator,
  rotateLeftCircularAccumulator,
  rotateRightAccumulator,
  rotateRightCircularAccumulator,
} from "./bitwise";
import {
  callFunction,
  callFunctionConditional,
  jump,
  jumpConditional,
  jumpToHL,
  relativeJump,
  relativeJumpConditional,
  restartFunction,
  returnFromFunction,
  returnFromFunctionConditional,
  returnFromInterruptHandler,
} from "./flow";
import { bindArgs, OpTable } from "./lib";
import {
  loadDirectFromStackPointer,
  loadHLFromAdjustedStackPointer,
  loadRegisterPair,
  loadStackPointerFromHL,
  popFromStack,
  pushToStack,
} from "./load16";
import {
  loadAccumulatorFromDirectByte,
  loadAccumulatorFromDirectWord,
  loadAccumulatorFromIndirectBC,
  loadAccumulatorFromIndirectC,
  loadAccumulatorFromIndirectDE,
  loadAccumulatorFromIndirectHLDecrement,
  loadAccumulatorFromIndirectHLIncrement,
  loadDirectByteFromAccumulator,
  loadDirectWordFromAccumulator,
  loadIndirectBCFromAccumulator,
  loadIndirectCFromAccumulator,
  loadIndirectDEFromAccumulator,
  loadIndirectHLDecrementFromAccumulator,
  loadIndirectHLFromImmediateData,
  loadIndirectHLFromRegister,
  loadIndirectHLIncrementFromAccumulator,
  loadRegisterFromImmediate,
  loadRegisterFromIndirectHL,
  loadRegisterFromRegister,
} from "./load8";
import {
  disableInterrupts,
  enableInterrupts,
  halt,
  noOperation,
  stop,
} from "./misc";

const instructions: OpTable = {
  0x00: ["NOP", noOperation],
  0x01: ["LD BC,d16", bindArgs(loadRegisterPair, RegisterPair.BC)],
  0x02: ["LD (BC),A", loadIndirectBCFromAccumulator],
  0x03: ["INC BC", bindArgs(incrementRegisterPair, RegisterPair.BC)],
  0x04: ["INC B", bindArgs(incrementRegister, Register.B)],
  0x05: ["DEC B", bindArgs(decrementRegister, Register.B)],
  0x06: ["LD B,d8", bindArgs(loadRegisterFromImmediate, Register.B)],
  0x07: ["RLCA", rotateLeftCircularAccumulator],
  0x08: ["LD (a16),SP", loadDirectFromStackPointer],
  0x09: ["ADD HL,BC", bindArgs(addRegisterPair, RegisterPair.BC)],
  0x0a: ["LD A,(BC)", loadAccumulatorFromIndirectBC],
  0x0b: ["DEC BC", bindArgs(decrementRegisterPair, RegisterPair.BC)],
  0x0c: ["INC C", bindArgs(incrementRegister, Register.C)],
  0x0d: ["DEC C", bindArgs(decrementRegister, Register.C)],
  0x0e: ["LD C,d8", bindArgs(loadRegisterFromImmediate, Register.C)],
  0x0f: ["RRCA", rotateRightCircularAccumulator],

  0x10: ["STOP 0", stop],
  0x11: ["LD DE,d16", bindArgs(loadRegisterPair, RegisterPair.DE)],
  0x12: ["LD (DE),A", loadIndirectDEFromAccumulator],
  0x13: ["INC DE", bindArgs(incrementRegisterPair, RegisterPair.DE)],
  0x14: ["INC D", bindArgs(incrementRegister, Register.D)],
  0x15: ["DEC D", bindArgs(decrementRegister, Register.D)],
  0x16: ["LD D,d8", bindArgs(loadRegisterFromImmediate, Register.D)],
  0x17: ["RLA", rotateLeftAccumulator],
  0x18: ["JR r8", relativeJump],
  0x19: ["ADD HL,DE", bindArgs(addRegisterPair, RegisterPair.DE)],
  0x1a: ["LD A,(DE)", loadAccumulatorFromIndirectDE],
  0x1b: ["DEC DE", bindArgs(decrementRegisterPair, RegisterPair.DE)],
  0x1c: ["INC E", bindArgs(incrementRegister, Register.E)],
  0x1d: ["DEC E", bindArgs(decrementRegister, Register.E)],
  0x1e: ["LD E,d8", bindArgs(loadRegisterFromImmediate, Register.E)],
  0x1f: ["RRA", rotateRightAccumulator],

  0x20: ["JR NZ,r8", bindArgs(relativeJumpConditional, Condition.NZ)],
  0x21: ["LD HL,d16", bindArgs(loadRegisterPair, RegisterPair.HL)],
  0x22: ["LD (HL+),A", loadIndirectHLIncrementFromAccumulator],
  0x23: ["INC HL", bindArgs(incrementRegisterPair, RegisterPair.HL)],
  0x24: ["INC H", bindArgs(incrementRegister, Register.H)],
  0x25: ["DEC H", bindArgs(decrementRegister, Register.H)],
  0x26: ["LD H,d8", bindArgs(loadRegisterFromImmediate, Register.H)],
  0x27: ["DAA", decimalAdjustAccumulator],
  0x28: ["JR Z,r8", bindArgs(relativeJumpConditional, Condition.Z)],
  0x29: ["ADD HL,HL", bindArgs(addRegisterPair, RegisterPair.HL)],
  0x2a: ["LD A,(HL+)", loadAccumulatorFromIndirectHLIncrement],
  0x2b: ["DEC HL", bindArgs(decrementRegisterPair, RegisterPair.HL)],
  0x2c: ["INC L", bindArgs(incrementRegister, Register.L)],
  0x2d: ["DEC L", bindArgs(decrementRegister, Register.L)],
  0x2e: ["LD L,d8", bindArgs(loadRegisterFromImmediate, Register.L)],
  0x2f: ["CPL", complementAccumulator],

  0x30: ["JR NC,r8", bindArgs(relativeJumpConditional, Condition.NC)],
  0x31: ["LD SP,d16", bindArgs(loadRegisterPair, RegisterPair.SP)],
  0x32: ["LD (HL-),A", loadIndirectHLDecrementFromAccumulator],
  0x33: ["INC SP", bindArgs(incrementRegisterPair, RegisterPair.SP)],
  0x34: ["INC (HL)", incrementIndirectHL],
  0x35: ["DEC (HL)", decrementIndirectHL],
  0x36: ["LD (HL),d8", loadIndirectHLFromImmediateData],
  0x37: ["SCF", setCarryFlag],
  0x38: ["JR C,r8", bindArgs(relativeJumpConditional, Condition.C)],
  0x39: ["ADD HL,SP", bindArgs(addRegisterPair, RegisterPair.SP)],
  0x3a: ["LD A,(HL-)", loadAccumulatorFromIndirectHLDecrement],
  0x3b: ["DEC SP", bindArgs(decrementRegisterPair, RegisterPair.SP)],
  0x3c: ["INC A", bindArgs(incrementRegister, Register.A)],
  0x3d: ["DEC A", bindArgs(decrementRegister, Register.A)],
  0x3e: ["LD A,d8", bindArgs(loadRegisterFromImmediate, Register.A)],
  0x3f: ["CCF", complementCarryFlag],

  0x40: ["LD B,B", bindArgs(loadRegisterFromRegister, Register.B, Register.B)],
  0x41: ["LD B,C", bindArgs(loadRegisterFromRegister, Register.B, Register.C)],
  0x42: ["LD B,D", bindArgs(loadRegisterFromRegister, Register.B, Register.D)],
  0x43: ["LD B,E", bindArgs(loadRegisterFromRegister, Register.B, Register.E)],
  0x44: ["LD B,H", bindArgs(loadRegisterFromRegister, Register.B, Register.H)],
  0x45: ["LD B,L", bindArgs(loadRegisterFromRegister, Register.B, Register.L)],
  0x46: ["LD B,(HL)", bindArgs(loadRegisterFromIndirectHL, Register.B)],
  0x47: ["LD B,A", bindArgs(loadRegisterFromRegister, Register.B, Register.A)],
  0x48: ["LD C,B", bindArgs(loadRegisterFromRegister, Register.C, Register.B)],
  0x49: ["LD C,C", bindArgs(loadRegisterFromRegister, Register.C, Register.C)],
  0x4a: ["LD C,D", bindArgs(loadRegisterFromRegister, Register.C, Register.D)],
  0x4b: ["LD C,E", bindArgs(loadRegisterFromRegister, Register.C, Register.E)],
  0x4c: ["LD C,H", bindArgs(loadRegisterFromRegister, Register.C, Register.H)],
  0x4d: ["LD C,L", bindArgs(loadRegisterFromRegister, Register.C, Register.L)],
  0x4e: ["LD C,(HL)", bindArgs(loadRegisterFromIndirectHL, Register.C)],
  0x4f: ["LD C,A", bindArgs(loadRegisterFromRegister, Register.C, Register.A)],

  0x50: ["LD D,B", bindArgs(loadRegisterFromRegister, Register.D, Register.B)],
  0x51: ["LD D,C", bindArgs(loadRegisterFromRegister, Register.D, Register.C)],
  0x52: ["LD D,D", bindArgs(loadRegisterFromRegister, Register.D, Register.D)],
  0x53: ["LD D,E", bindArgs(loadRegisterFromRegister, Register.D, Register.E)],
  0x54: ["LD D,H", bindArgs(loadRegisterFromRegister, Register.D, Register.H)],
  0x55: ["LD D,L", bindArgs(loadRegisterFromRegister, Register.D, Register.L)],
  0x56: ["LD D,(HL)", bindArgs(loadRegisterFromIndirectHL, Register.D)],
  0x57: ["LD D,A", bindArgs(loadRegisterFromRegister, Register.D, Register.A)],
  0x58: ["LD E,B", bindArgs(loadRegisterFromRegister, Register.E, Register.B)],
  0x59: ["LD E,C", bindArgs(loadRegisterFromRegister, Register.E, Register.C)],
  0x5a: ["LD E,D", bindArgs(loadRegisterFromRegister, Register.E, Register.D)],
  0x5b: ["LD E,E", bindArgs(loadRegisterFromRegister, Register.E, Register.E)],
  0x5c: ["LD E,H", bindArgs(loadRegisterFromRegister, Register.E, Register.H)],
  0x5d: ["LD E,L", bindArgs(loadRegisterFromRegister, Register.E, Register.L)],
  0x5e: ["LD E,(HL)", bindArgs(loadRegisterFromIndirectHL, Register.E)],
  0x5f: ["LD E,A", bindArgs(loadRegisterFromRegister, Register.E, Register.A)],

  0x60: ["LD H,B", bindArgs(loadRegisterFromRegister, Register.H, Register.B)],
  0x61: ["LD H,C", bindArgs(loadRegisterFromRegister, Register.H, Register.C)],
  0x62: ["LD H,D", bindArgs(loadRegisterFromRegister, Register.H, Register.D)],
  0x63: ["LD H,E", bindArgs(loadRegisterFromRegister, Register.H, Register.E)],
  0x64: ["LD H,H", bindArgs(loadRegisterFromRegister, Register.H, Register.H)],
  0x65: ["LD H,L", bindArgs(loadRegisterFromRegister, Register.H, Register.L)],
  0x66: ["LD H,(HL)", bindArgs(loadRegisterFromIndirectHL, Register.H)],
  0x67: ["LD H,A", bindArgs(loadRegisterFromRegister, Register.H, Register.A)],
  0x68: ["LD L,B", bindArgs(loadRegisterFromRegister, Register.L, Register.B)],
  0x69: ["LD L,C", bindArgs(loadRegisterFromRegister, Register.L, Register.C)],
  0x6a: ["LD L,D", bindArgs(loadRegisterFromRegister, Register.L, Register.D)],
  0x6b: ["LD L,E", bindArgs(loadRegisterFromRegister, Register.L, Register.E)],
  0x6c: ["LD L,H", bindArgs(loadRegisterFromRegister, Register.L, Register.H)],
  0x6d: ["LD L,L", bindArgs(loadRegisterFromRegister, Register.L, Register.L)],
  0x6e: ["LD L,(HL)", bindArgs(loadRegisterFromIndirectHL, Register.L)],
  0x6f: ["LD L,A", bindArgs(loadRegisterFromRegister, Register.L, Register.A)],

  0x70: ["LD (HL),B", bindArgs(loadIndirectHLFromRegister, Register.B)],
  0x71: ["LD (HL),C", bindArgs(loadIndirectHLFromRegister, Register.C)],
  0x72: ["LD (HL),D", bindArgs(loadIndirectHLFromRegister, Register.D)],
  0x73: ["LD (HL),E", bindArgs(loadIndirectHLFromRegister, Register.E)],
  0x74: ["LD (HL),H", bindArgs(loadIndirectHLFromRegister, Register.H)],
  0x75: ["LD (HL),L", bindArgs(loadIndirectHLFromRegister, Register.L)],
  0x76: ["HALT", halt],
  0x77: ["LD (HL),A", bindArgs(loadIndirectHLFromRegister, Register.A)],
  0x78: ["LD A,B", bindArgs(loadRegisterFromRegister, Register.A, Register.B)],
  0x79: ["LD A,C", bindArgs(loadRegisterFromRegister, Register.A, Register.C)],
  0x7a: ["LD A,D", bindArgs(loadRegisterFromRegister, Register.A, Register.D)],
  0x7b: ["LD A,E", bindArgs(loadRegisterFromRegister, Register.A, Register.E)],
  0x7c: ["LD A,H", bindArgs(loadRegisterFromRegister, Register.A, Register.H)],
  0x7d: ["LD A,L", bindArgs(loadRegisterFromRegister, Register.A, Register.L)],
  0x7e: ["LD A,(HL)", bindArgs(loadRegisterFromIndirectHL, Register.A)],
  0x7f: ["LD A,A", bindArgs(loadRegisterFromRegister, Register.A, Register.A)],

  0x80: ["ADD A,B", bindArgs(addRegister, Register.B)],
  0x81: ["ADD A,C", bindArgs(addRegister, Register.C)],
  0x82: ["ADD A,D", bindArgs(addRegister, Register.D)],
  0x83: ["ADD A,E", bindArgs(addRegister, Register.E)],
  0x84: ["ADD A,H", bindArgs(addRegister, Register.H)],
  0x85: ["ADD A,L", bindArgs(addRegister, Register.L)],
  0x86: ["ADD A,(HL)", addIndirectHL],
  0x87: ["ADD A,A", bindArgs(addRegister, Register.A)],
  0x88: ["ADC A,B", bindArgs(addRegisterWithCarry, Register.B)],
  0x89: ["ADC A,C", bindArgs(addRegisterWithCarry, Register.C)],
  0x8a: ["ADC A,D", bindArgs(addRegisterWithCarry, Register.D)],
  0x8b: ["ADC A,E", bindArgs(addRegisterWithCarry, Register.E)],
  0x8c: ["ADC A,H", bindArgs(addRegisterWithCarry, Register.H)],
  0x8d: ["ADC A,L", bindArgs(addRegisterWithCarry, Register.L)],
  0x8e: ["ADC A,(HL)", addIndirectHLWithCarry],
  0x8f: ["ADC A,A", bindArgs(addRegisterWithCarry, Register.A)],

  0x90: ["SUB B", bindArgs(subtractRegister, Register.B)],
  0x91: ["SUB C", bindArgs(subtractRegister, Register.C)],
  0x92: ["SUB D", bindArgs(subtractRegister, Register.D)],
  0x93: ["SUB E", bindArgs(subtractRegister, Register.E)],
  0x94: ["SUB H", bindArgs(subtractRegister, Register.H)],
  0x95: ["SUB L", bindArgs(subtractRegister, Register.L)],
  0x96: ["SUB (HL)", subtractIndirectHL],
  0x97: ["SUB A", bindArgs(subtractRegister, Register.A)],
  0x98: ["SBC A,B", bindArgs(subtractRegisterWithCarry, Register.B)],
  0x99: ["SBC A,C", bindArgs(subtractRegisterWithCarry, Register.C)],
  0x9a: ["SBC A,D", bindArgs(subtractRegisterWithCarry, Register.D)],
  0x9b: ["SBC A,E", bindArgs(subtractRegisterWithCarry, Register.E)],
  0x9c: ["SBC A,H", bindArgs(subtractRegisterWithCarry, Register.H)],
  0x9d: ["SBC A,L", bindArgs(subtractRegisterWithCarry, Register.L)],
  0x9e: ["SBC A,(HL)", subtractIndirectHLWithCarry],
  0x9f: ["SBC A,A", bindArgs(subtractRegisterWithCarry, Register.A)],

  0xa0: ["AND B", bindArgs(andRegister, Register.B)],
  0xa1: ["AND C", bindArgs(andRegister, Register.C)],
  0xa2: ["AND D", bindArgs(andRegister, Register.D)],
  0xa3: ["AND E", bindArgs(andRegister, Register.E)],
  0xa4: ["AND H", bindArgs(andRegister, Register.H)],
  0xa5: ["AND L", bindArgs(andRegister, Register.L)],
  0xa6: ["AND (HL)", andIndirectHL],
  0xa7: ["AND A", bindArgs(andRegister, Register.A)],
  0xa8: ["XOR B", bindArgs(xorRegister, Register.B)],
  0xa9: ["XOR C", bindArgs(xorRegister, Register.C)],
  0xaa: ["XOR D", bindArgs(xorRegister, Register.D)],
  0xab: ["XOR E", bindArgs(xorRegister, Register.E)],
  0xac: ["XOR H", bindArgs(xorRegister, Register.H)],
  0xad: ["XOR L", bindArgs(xorRegister, Register.L)],
  0xae: ["XOR (HL)", xorIndirectHL],
  0xaf: ["XOR A", bindArgs(xorRegister, Register.A)],

  0xb0: ["OR B", bindArgs(orRegister, Register.B)],
  0xb1: ["OR C", bindArgs(orRegister, Register.C)],
  0xb2: ["OR D", bindArgs(orRegister, Register.D)],
  0xb3: ["OR E", bindArgs(orRegister, Register.E)],
  0xb4: ["OR H", bindArgs(orRegister, Register.H)],
  0xb5: ["OR L", bindArgs(orRegister, Register.L)],
  0xb6: ["OR (HL)", orIndirectHL],
  0xb7: ["OR A", bindArgs(orRegister, Register.A)],
  0xb8: ["CP B", bindArgs(compareRegister, Register.B)],
  0xb9: ["CP C", bindArgs(compareRegister, Register.C)],
  0xba: ["CP D", bindArgs(compareRegister, Register.D)],
  0xbb: ["CP E", bindArgs(compareRegister, Register.E)],
  0xbc: ["CP H", bindArgs(compareRegister, Register.H)],
  0xbd: ["CP L", bindArgs(compareRegister, Register.L)],
  0xbe: ["CP (HL)", compareIndirectHL],
  0xbf: ["CP A", bindArgs(compareRegister, Register.A)],

  0xc0: ["RET NZ", bindArgs(returnFromFunctionConditional, Condition.NZ)],
  0xc1: ["POP BC", bindArgs(popFromStack, RegisterPair.BC)],
  0xc2: ["JP NZ,a16", bindArgs(jumpConditional, Condition.NZ)],
  0xc3: ["JP a16", jump],
  0xc4: ["CALL NZ,a16", bindArgs(callFunctionConditional, Condition.NZ)],
  0xc5: ["PUSH BC", bindArgs(pushToStack, RegisterPair.BC)],
  0xc6: ["ADD A,d8", addImmediate],
  0xc7: ["RST 00H", bindArgs(restartFunction, 0x00)],
  0xc8: ["RET Z", bindArgs(returnFromFunctionConditional, Condition.Z)],
  0xc9: ["RET", returnFromFunction],
  0xca: ["JP Z,a16", bindArgs(jumpConditional, Condition.Z)],
  // 0xcb: prefix CB
  0xcc: ["CALL Z,a16", bindArgs(callFunctionConditional, Condition.Z)],
  0xcd: ["CALL a16", callFunction],
  0xce: ["ADC A,d8", addImmediateWithCarry],
  0xcf: ["RST 08H", bindArgs(restartFunction, 0x08)],

  0xd0: ["RET NC", bindArgs(returnFromFunctionConditional, Condition.NC)],
  0xd1: ["POP BC", bindArgs(popFromStack, RegisterPair.DE)],
  0xd2: ["JP NC,a16", bindArgs(jumpConditional, Condition.NC)],
  0xd4: ["CALL NC,a16", bindArgs(callFunctionConditional, Condition.NC)],
  0xd5: ["PUSH DE", bindArgs(pushToStack, RegisterPair.DE)],
  0xd6: ["SUB d8", subtractImmediate],
  0xd7: ["RST 10H", bindArgs(restartFunction, 0x10)],
  0xd8: ["RET C", bindArgs(returnFromFunctionConditional, Condition.C)],
  0xd9: ["RETI", returnFromInterruptHandler],
  0xda: ["JP C,a16", bindArgs(jumpConditional, Condition.C)],
  0xdc: ["CALL C,a16", bindArgs(callFunctionConditional, Condition.C)],
  0xde: ["SBC A,d8", subtractImmediateWithCarry],
  0xdf: ["RST 18H", bindArgs(restartFunction, 0x18)],

  0xe0: ["LDH (a8),A", loadDirectByteFromAccumulator],
  0xe1: ["POP BC", bindArgs(popFromStack, RegisterPair.HL)],
  0xe2: ["LD (s),A", loadIndirectCFromAccumulator],
  0xe5: ["PUSH HL", bindArgs(pushToStack, RegisterPair.HL)],
  0xe6: ["AND d8", andImmediate],
  0xe7: ["RST 20H", bindArgs(restartFunction, 0x20)],
  0xe8: ["ADD SP,r8", addToStackPointer],
  0xe9: ["JP (HL)", jumpToHL],
  0xea: ["LD (a16),A", loadDirectWordFromAccumulator],
  0xee: ["XOR d8", xorImmediate],
  0xef: ["RST 28H", bindArgs(restartFunction, 0x28)],

  0xf0: ["LDH A,(a8)", loadAccumulatorFromDirectByte],
  0xf1: ["POP AF", bindArgs(popFromStack, RegisterPair.AF)],
  0xf2: ["LD A,(s)", loadAccumulatorFromIndirectC],
  0xf3: ["DI", disableInterrupts],
  0xf5: ["PUSH AF", bindArgs(pushToStack, RegisterPair.AF)],
  0xf6: ["AND d8", orImmediate],
  0xf7: ["RST 30H", bindArgs(restartFunction, 0x30)],
  0xf8: ["LD HL,SP+r8", loadHLFromAdjustedStackPointer],
  0xf9: ["LD SP,HL", loadStackPointerFromHL],
  0xfa: ["LD A,(a16)", loadAccumulatorFromDirectWord],
  0xfb: ["EI", enableInterrupts],
  0xfe: ["CP d8", compareImmediate],
  0xff: ["RST 38H", bindArgs(restartFunction, 0x38)],
};

export function getInstruction(opcode: number) {
  return instructions[opcode];
}
