import { CpuState, fetchImmediateByte } from "../cpu-state";
import { RegisterPair, Register } from "../regs";

import {
  addRegisterPair,
  addToStackPointer,
  decrementRegisterPair,
  incrementRegisterPair,
} from "./arithmetic16";
import {
  addImmediate,
  addImmediateWithCarry,
  addIndirectHL,
  addIndirectHLWithCarry,
  addRegister,
  addRegisterWithCarry,
  andImmediate,
  andIndirectHL,
  andRegister,
  compareImmediate,
  compareIndirectHL,
  compareRegister,
  complementAccumulator,
  complementCarryFlag,
  decimalAdjustAccumulator,
  decrementIndirectHL,
  decrementRegister,
  incrementIndirectHL,
  incrementRegister,
  orImmediate,
  orIndirectHL,
  orRegister,
  setCarryFlag,
  subtractImmediate,
  subtractImmediateWithCarry,
  subtractIndirectHL,
  subtractIndirectHLWithCarry,
  subtractRegister,
  subtractRegisterWithCarry,
  xorImmediate,
  xorIndirectHL,
  xorRegister,
} from "./arithmetic8";
import {
  rotateLeftAccumulator,
  rotateLeftCircularAccumulator,
  rotateRightAccumulator,
  rotateRightCircularAccumulator,
} from "./bitwise";
import {
  callFunction,
  callFunctionConditional,
  jump,
  jumpConditional,
  jumpToHL,
  relativeJump,
  relativeJumpConditional,
  restartFunction,
  returnFromFunction,
  returnFromFunctionConditional,
  returnFromInterruptHandler,
} from "./flow";
import { OpTable } from "./lib";
import {
  loadDirectFromStackPointer,
  loadHLFromAdjustedStackPointer,
  loadRegisterPair,
  loadStackPointerFromHL,
  popFromStack,
  pushToStack,
} from "./load16";
import {
  loadAccumulatorFromDirectByte,
  loadAccumulatorFromDirectWord,
  loadAccumulatorFromIndirectBC,
  loadAccumulatorFromIndirectC,
  loadAccumulatorFromIndirectDE,
  loadAccumulatorFromIndirectHLDecrement,
  loadAccumulatorFromIndirectHLIncrement,
  loadDirectByteFromAccumulator,
  loadDirectWordFromAccumulator,
  loadIndirectBCFromAccumulator,
  loadIndirectCFromAccumulator,
  loadIndirectDEFromAccumulator,
  loadIndirectHLDecrementFromAccumulator,
  loadIndirectHLFromImmediateData,
  loadIndirectHLFromRegister,
  loadIndirectHLIncrementFromAccumulator,
  loadRegisterFromImmediate,
  loadRegisterFromIndirectHL,
  loadRegisterFromRegister,
} from "./load8";
import {
  disableInterrupts,
  enableInterrupts,
  halt,
  noOperation,
  stop,
} from "./misc";
import { getNextPrefixCbInstruction } from "./prefixed-optable";

const instructions: OpTable = {
  0x00: ["NOP", noOperation],
  0x01: ["LD BC,d16", (s) => loadRegisterPair(s, RegisterPair.BC)],
  0x02: ["LD (BC),A", loadIndirectBCFromAccumulator],
  0x03: ["INC BC", (s) => incrementRegisterPair(s, RegisterPair.BC)],
  0x04: ["INC B", (s) => incrementRegister(s, Register.B)],
  0x05: ["DEC B", (s) => decrementRegister(s, Register.B)],
  0x06: ["LD B,d8", (s) => loadRegisterFromImmediate(s, Register.B)],
  0x07: ["RLCA", rotateLeftCircularAccumulator],
  0x08: ["LD (a16),SP", loadDirectFromStackPointer],
  0x09: ["ADD HL,BC", (s) => addRegisterPair(s, RegisterPair.BC)],
  0x0a: ["LD A,(BC)", loadAccumulatorFromIndirectBC],
  0x0b: ["DEC BC", (s) => decrementRegisterPair(s, RegisterPair.BC)],
  0x0c: ["INC C", (s) => incrementRegister(s, Register.C)],
  0x0d: ["DEC C", (s) => decrementRegister(s, Register.C)],
  0x0e: ["LD C,d8", (s) => loadRegisterFromImmediate(s, Register.C)],
  0x0f: ["RRCA", rotateRightCircularAccumulator],

  0x10: ["STOP 0", stop],
  0x11: ["LD DE,d16", (s) => loadRegisterPair(s, RegisterPair.DE)],
  0x12: ["LD (DE),A", loadIndirectDEFromAccumulator],
  0x13: ["INC DE", (s) => incrementRegisterPair(s, RegisterPair.DE)],
  0x14: ["INC D", (s) => incrementRegister(s, Register.D)],
  0x15: ["DEC D", (s) => decrementRegister(s, Register.D)],
  0x16: ["LD D,d8", (s) => loadRegisterFromImmediate(s, Register.D)],
  0x17: ["RLA", rotateLeftAccumulator],
  0x18: ["JR r8", relativeJump],
  0x19: ["ADD HL,DE", (s) => addRegisterPair(s, RegisterPair.DE)],
  0x1a: ["LD A,(DE)", loadAccumulatorFromIndirectDE],
  0x1b: ["DEC DE", (s) => decrementRegisterPair(s, RegisterPair.DE)],
  0x1c: ["INC E", (s) => incrementRegister(s, Register.E)],
  0x1d: ["DEC E", (s) => decrementRegister(s, Register.E)],
  0x1e: ["LD E,d8", (s) => loadRegisterFromImmediate(s, Register.E)],
  0x1f: ["RRA", rotateRightAccumulator],

  0x20: ["JR NZ,r8", (s) => relativeJumpConditional(s, "NZ")],
  0x21: ["LD HL,d16", (s) => loadRegisterPair(s, RegisterPair.HL)],
  0x22: ["LD (HL+),A", loadIndirectHLIncrementFromAccumulator],
  0x23: ["INC HL", (s) => incrementRegisterPair(s, RegisterPair.HL)],
  0x24: ["INC H", (s) => incrementRegister(s, Register.H)],
  0x25: ["DEC H", (s) => decrementRegister(s, Register.H)],
  0x26: ["LD H,d8", (s) => loadRegisterFromImmediate(s, Register.H)],
  0x27: ["DAA", decimalAdjustAccumulator],
  0x28: ["JR Z,r8", (s) => relativeJumpConditional(s, "Z")],
  0x29: ["ADD HL,HL", (s) => addRegisterPair(s, RegisterPair.HL)],
  0x2a: ["LD A,(HL+)", loadAccumulatorFromIndirectHLIncrement],
  0x2b: ["DEC HL", (s) => decrementRegisterPair(s, RegisterPair.HL)],
  0x2c: ["INC L", (s) => incrementRegister(s, Register.L)],
  0x2d: ["DEC L", (s) => decrementRegister(s, Register.L)],
  0x2e: ["LD L,d8", (s) => loadRegisterFromImmediate(s, Register.L)],
  0x2f: ["CPL", complementAccumulator],

  0x30: ["JR NC,r8", (s) => relativeJumpConditional(s, "NC")],
  0x31: ["LD SP,d16", (s) => loadRegisterPair(s, RegisterPair.SP)],
  0x32: ["LD (HL-),A", loadIndirectHLDecrementFromAccumulator],
  0x33: ["INC SP", (s) => incrementRegisterPair(s, RegisterPair.SP)],
  0x34: ["INC (HL)", incrementIndirectHL],
  0x35: ["DEC (HL)", decrementIndirectHL],
  0x36: ["LD (HL),d8", loadIndirectHLFromImmediateData],
  0x37: ["SCF", setCarryFlag],
  0x38: ["JR C,r8", (s) => relativeJumpConditional(s, "C")],
  0x39: ["ADD HL,SP", (s) => addRegisterPair(s, RegisterPair.SP)],
  0x3a: ["LD A,(HL-)", loadAccumulatorFromIndirectHLDecrement],
  0x3b: ["DEC SP", (s) => decrementRegisterPair(s, RegisterPair.SP)],
  0x3c: ["INC A", (s) => incrementRegister(s, Register.A)],
  0x3d: ["DEC A", (s) => decrementRegister(s, Register.A)],
  0x3e: ["LD A,d8", (s) => loadRegisterFromImmediate(s, Register.A)],
  0x3f: ["CCF", complementCarryFlag],

  0x40: ["LD B,B", (s) => loadRegisterFromRegister(s, Register.B, Register.B)],
  0x41: ["LD B,C", (s) => loadRegisterFromRegister(s, Register.B, Register.C)],
  0x42: ["LD B,D", (s) => loadRegisterFromRegister(s, Register.B, Register.D)],
  0x43: ["LD B,E", (s) => loadRegisterFromRegister(s, Register.B, Register.E)],
  0x44: ["LD B,H", (s) => loadRegisterFromRegister(s, Register.B, Register.H)],
  0x45: ["LD B,L", (s) => loadRegisterFromRegister(s, Register.B, Register.L)],
  0x46: ["LD B,(HL)", (s) => loadRegisterFromIndirectHL(s, Register.B)],
  0x47: ["LD B,A", (s) => loadRegisterFromRegister(s, Register.B, Register.A)],
  0x48: ["LD C,B", (s) => loadRegisterFromRegister(s, Register.C, Register.B)],
  0x49: ["LD C,C", (s) => loadRegisterFromRegister(s, Register.C, Register.C)],
  0x4a: ["LD C,D", (s) => loadRegisterFromRegister(s, Register.C, Register.D)],
  0x4b: ["LD C,E", (s) => loadRegisterFromRegister(s, Register.C, Register.E)],
  0x4c: ["LD C,H", (s) => loadRegisterFromRegister(s, Register.C, Register.H)],
  0x4d: ["LD C,L", (s) => loadRegisterFromRegister(s, Register.C, Register.L)],
  0x4e: ["LD C,(HL)", (s) => loadRegisterFromIndirectHL(s, Register.C)],
  0x4f: ["LD C,A", (s) => loadRegisterFromRegister(s, Register.C, Register.A)],

  0x50: ["LD D,B", (s) => loadRegisterFromRegister(s, Register.D, Register.B)],
  0x51: ["LD D,C", (s) => loadRegisterFromRegister(s, Register.D, Register.C)],
  0x52: ["LD D,D", (s) => loadRegisterFromRegister(s, Register.D, Register.D)],
  0x53: ["LD D,E", (s) => loadRegisterFromRegister(s, Register.D, Register.E)],
  0x54: ["LD D,H", (s) => loadRegisterFromRegister(s, Register.D, Register.H)],
  0x55: ["LD D,L", (s) => loadRegisterFromRegister(s, Register.D, Register.L)],
  0x56: ["LD D,(HL)", (s) => loadRegisterFromIndirectHL(s, Register.D)],
  0x57: ["LD D,A", (s) => loadRegisterFromRegister(s, Register.D, Register.A)],
  0x58: ["LD E,B", (s) => loadRegisterFromRegister(s, Register.E, Register.B)],
  0x59: ["LD E,C", (s) => loadRegisterFromRegister(s, Register.E, Register.C)],
  0x5a: ["LD E,D", (s) => loadRegisterFromRegister(s, Register.E, Register.D)],
  0x5b: ["LD E,E", (s) => loadRegisterFromRegister(s, Register.E, Register.E)],
  0x5c: ["LD E,H", (s) => loadRegisterFromRegister(s, Register.E, Register.H)],
  0x5d: ["LD E,L", (s) => loadRegisterFromRegister(s, Register.E, Register.L)],
  0x5e: ["LD E,(HL)", (s) => loadRegisterFromIndirectHL(s, Register.E)],
  0x5f: ["LD E,A", (s) => loadRegisterFromRegister(s, Register.E, Register.A)],

  0x60: ["LD H,B", (s) => loadRegisterFromRegister(s, Register.H, Register.B)],
  0x61: ["LD H,C", (s) => loadRegisterFromRegister(s, Register.H, Register.C)],
  0x62: ["LD H,D", (s) => loadRegisterFromRegister(s, Register.H, Register.D)],
  0x63: ["LD H,E", (s) => loadRegisterFromRegister(s, Register.H, Register.E)],
  0x64: ["LD H,H", (s) => loadRegisterFromRegister(s, Register.H, Register.H)],
  0x65: ["LD H,L", (s) => loadRegisterFromRegister(s, Register.H, Register.L)],
  0x66: ["LD H,(HL)", (s) => loadRegisterFromIndirectHL(s, Register.H)],
  0x67: ["LD H,A", (s) => loadRegisterFromRegister(s, Register.H, Register.A)],
  0x68: ["LD L,B", (s) => loadRegisterFromRegister(s, Register.L, Register.B)],
  0x69: ["LD L,C", (s) => loadRegisterFromRegister(s, Register.L, Register.C)],
  0x6a: ["LD L,D", (s) => loadRegisterFromRegister(s, Register.L, Register.D)],
  0x6b: ["LD L,E", (s) => loadRegisterFromRegister(s, Register.L, Register.E)],
  0x6c: ["LD L,H", (s) => loadRegisterFromRegister(s, Register.L, Register.H)],
  0x6d: ["LD L,L", (s) => loadRegisterFromRegister(s, Register.L, Register.L)],
  0x6e: ["LD L,(HL)", (s) => loadRegisterFromIndirectHL(s, Register.L)],
  0x6f: ["LD L,A", (s) => loadRegisterFromRegister(s, Register.L, Register.A)],

  0x70: ["LD (HL),B", (s) => loadIndirectHLFromRegister(s, Register.B)],
  0x71: ["LD (HL),C", (s) => loadIndirectHLFromRegister(s, Register.C)],
  0x72: ["LD (HL),D", (s) => loadIndirectHLFromRegister(s, Register.D)],
  0x73: ["LD (HL),E", (s) => loadIndirectHLFromRegister(s, Register.E)],
  0x74: ["LD (HL),H", (s) => loadIndirectHLFromRegister(s, Register.H)],
  0x75: ["LD (HL),L", (s) => loadIndirectHLFromRegister(s, Register.L)],
  0x76: ["HALT", halt],
  0x77: ["LD (HL),A", (s) => loadIndirectHLFromRegister(s, Register.A)],
  0x78: ["LD A,B", (s) => loadRegisterFromRegister(s, Register.A, Register.B)],
  0x79: ["LD A,C", (s) => loadRegisterFromRegister(s, Register.A, Register.C)],
  0x7a: ["LD A,D", (s) => loadRegisterFromRegister(s, Register.A, Register.D)],
  0x7b: ["LD A,E", (s) => loadRegisterFromRegister(s, Register.A, Register.E)],
  0x7c: ["LD A,H", (s) => loadRegisterFromRegister(s, Register.A, Register.H)],
  0x7d: ["LD A,L", (s) => loadRegisterFromRegister(s, Register.A, Register.L)],
  0x7e: ["LD A,(HL)", (s) => loadRegisterFromIndirectHL(s, Register.A)],
  0x7f: ["LD A,A", (s) => loadRegisterFromRegister(s, Register.A, Register.A)],

  0x80: ["ADD A,B", (s) => addRegister(s, Register.B)],
  0x81: ["ADD A,C", (s) => addRegister(s, Register.C)],
  0x82: ["ADD A,D", (s) => addRegister(s, Register.D)],
  0x83: ["ADD A,E", (s) => addRegister(s, Register.E)],
  0x84: ["ADD A,H", (s) => addRegister(s, Register.H)],
  0x85: ["ADD A,L", (s) => addRegister(s, Register.L)],
  0x86: ["ADD A,(HL)", addIndirectHL],
  0x87: ["ADD A,A", (s) => addRegister(s, Register.A)],
  0x88: ["ADC A,B", (s) => addRegisterWithCarry(s, Register.B)],
  0x89: ["ADC A,C", (s) => addRegisterWithCarry(s, Register.C)],
  0x8a: ["ADC A,D", (s) => addRegisterWithCarry(s, Register.D)],
  0x8b: ["ADC A,E", (s) => addRegisterWithCarry(s, Register.E)],
  0x8c: ["ADC A,H", (s) => addRegisterWithCarry(s, Register.H)],
  0x8d: ["ADC A,L", (s) => addRegisterWithCarry(s, Register.L)],
  0x8e: ["ADC A,(HL)", addIndirectHLWithCarry],
  0x8f: ["ADC A,A", (s) => addRegisterWithCarry(s, Register.A)],

  0x90: ["SUB B", (s) => subtractRegister(s, Register.B)],
  0x91: ["SUB C", (s) => subtractRegister(s, Register.C)],
  0x92: ["SUB D", (s) => subtractRegister(s, Register.D)],
  0x93: ["SUB E", (s) => subtractRegister(s, Register.E)],
  0x94: ["SUB H", (s) => subtractRegister(s, Register.H)],
  0x95: ["SUB L", (s) => subtractRegister(s, Register.L)],
  0x96: ["SUB (HL)", subtractIndirectHL],
  0x97: ["SUB A", (s) => subtractRegister(s, Register.A)],
  0x98: ["SBC A,B", (s) => subtractRegisterWithCarry(s, Register.B)],
  0x99: ["SBC A,C", (s) => subtractRegisterWithCarry(s, Register.C)],
  0x9a: ["SBC A,D", (s) => subtractRegisterWithCarry(s, Register.D)],
  0x9b: ["SBC A,E", (s) => subtractRegisterWithCarry(s, Register.E)],
  0x9c: ["SBC A,H", (s) => subtractRegisterWithCarry(s, Register.H)],
  0x9d: ["SBC A,L", (s) => subtractRegisterWithCarry(s, Register.L)],
  0x9e: ["SBC A,(HL)", subtractIndirectHLWithCarry],
  0x9f: ["SBC A,A", (s) => subtractRegisterWithCarry(s, Register.A)],

  0xa0: ["AND B", (s) => andRegister(s, Register.B)],
  0xa1: ["AND C", (s) => andRegister(s, Register.C)],
  0xa2: ["AND D", (s) => andRegister(s, Register.D)],
  0xa3: ["AND E", (s) => andRegister(s, Register.E)],
  0xa4: ["AND H", (s) => andRegister(s, Register.H)],
  0xa5: ["AND L", (s) => andRegister(s, Register.L)],
  0xa6: ["AND (HL)", andIndirectHL],
  0xa7: ["AND A", (s) => andRegister(s, Register.A)],
  0xa8: ["XOR B", (s) => xorRegister(s, Register.B)],
  0xa9: ["XOR C", (s) => xorRegister(s, Register.C)],
  0xaa: ["XOR D", (s) => xorRegister(s, Register.D)],
  0xab: ["XOR E", (s) => xorRegister(s, Register.E)],
  0xac: ["XOR H", (s) => xorRegister(s, Register.H)],
  0xad: ["XOR L", (s) => xorRegister(s, Register.L)],
  0xae: ["XOR (HL)", xorIndirectHL],
  0xaf: ["XOR A", (s) => xorRegister(s, Register.A)],

  0xb0: ["OR B", (s) => orRegister(s, Register.B)],
  0xb1: ["OR C", (s) => orRegister(s, Register.C)],
  0xb2: ["OR D", (s) => orRegister(s, Register.D)],
  0xb3: ["OR E", (s) => orRegister(s, Register.E)],
  0xb4: ["OR H", (s) => orRegister(s, Register.H)],
  0xb5: ["OR L", (s) => orRegister(s, Register.L)],
  0xb6: ["OR (HL)", orIndirectHL],
  0xb7: ["OR A", (s) => orRegister(s, Register.A)],
  0xb8: ["CP B", (s) => compareRegister(s, Register.B)],
  0xb9: ["CP C", (s) => compareRegister(s, Register.C)],
  0xba: ["CP D", (s) => compareRegister(s, Register.D)],
  0xbb: ["CP E", (s) => compareRegister(s, Register.E)],
  0xbc: ["CP H", (s) => compareRegister(s, Register.H)],
  0xbd: ["CP L", (s) => compareRegister(s, Register.L)],
  0xbe: ["CP (HL)", compareIndirectHL],
  0xbf: ["CP A", (s) => compareRegister(s, Register.A)],

  0xc0: ["RET NZ", (s) => returnFromFunctionConditional(s, "NZ")],
  0xc1: ["POP BC", (s) => popFromStack(s, RegisterPair.BC)],
  0xc2: ["JP NZ,a16", (s) => jumpConditional(s, "NZ")],
  0xc3: ["JP a16", jump],
  0xc4: ["CALL NZ,a16", (s) => callFunctionConditional(s, "NZ")],
  0xc5: ["PUSH BC", (s) => pushToStack(s, RegisterPair.BC)],
  0xc6: ["ADD A,d8", addImmediate],
  0xc7: ["RST 00H", (s) => restartFunction(s, 0x00)],
  0xc8: ["RET Z", (s) => returnFromFunctionConditional(s, "Z")],
  0xc9: ["RET", returnFromFunction],
  0xca: ["JP Z,a16", (s) => jumpConditional(s, "Z")],
  // 0xcb: prefix CB
  0xcc: ["CALL Z,a16", (s) => callFunctionConditional(s, "Z")],
  0xcd: ["CALL a16", callFunction],
  0xce: ["ADC A,d8", addImmediateWithCarry],
  0xcf: ["RST 08H", (s) => restartFunction(s, 0x08)],

  0xd0: ["RET NC", (s) => returnFromFunctionConditional(s, "NC")],
  0xd1: ["POP BC", (s) => popFromStack(s, RegisterPair.DE)],
  0xd2: ["JP NC,a16", (s) => jumpConditional(s, "NC")],
  0xd4: ["CALL NC,a16", (s) => callFunctionConditional(s, "NC")],
  0xd5: ["PUSH DE", (s) => pushToStack(s, RegisterPair.DE)],
  0xd6: ["SUB d8", subtractImmediate],
  0xd7: ["RST 10H", (s) => restartFunction(s, 0x10)],
  0xd8: ["RET C", (s) => returnFromFunctionConditional(s, "C")],
  0xd9: ["RETI", returnFromInterruptHandler],
  0xda: ["JP C,a16", (s) => jumpConditional(s, "C")],
  0xdc: ["CALL C,a16", (s) => callFunctionConditional(s, "C")],
  0xde: ["SBC A,d8", subtractImmediateWithCarry],
  0xdf: ["RST 18H", (s) => restartFunction(s, 0x18)],

  0xe0: ["LDH (a8),A", loadDirectByteFromAccumulator],
  0xe1: ["POP BC", (s) => popFromStack(s, RegisterPair.HL)],
  0xe2: ["LD (s),A", loadIndirectCFromAccumulator],
  0xe5: ["PUSH HL", (s) => pushToStack(s, RegisterPair.HL)],
  0xe6: ["AND d8", andImmediate],
  0xe7: ["RST 20H", (s) => restartFunction(s, 0x20)],
  0xe8: ["ADD SP,r8", addToStackPointer],
  0xe9: ["JP (HL)", jumpToHL],
  0xea: ["LD (a16),A", loadDirectWordFromAccumulator],
  0xee: ["XOR d8", xorImmediate],
  0xef: ["RST 28H", (s) => restartFunction(s, 0x28)],

  0xf0: ["LDH A,(a8)", loadAccumulatorFromDirectByte],
  0xf1: ["POP AF", (s) => popFromStack(s, RegisterPair.AF)],
  0xf2: ["LD A,(s)", loadAccumulatorFromIndirectC],
  0xf3: ["DI", disableInterrupts],
  0xf5: ["PUSH AF", (s) => pushToStack(s, RegisterPair.AF)],
  0xf6: ["AND d8", orImmediate],
  0xf7: ["RST 30H", (s) => restartFunction(s, 0x30)],
  0xf8: ["LD HL,SP+r8", loadHLFromAdjustedStackPointer],
  0xf9: ["LD SP,HL", loadStackPointerFromHL],
  0xfa: ["LD A,(a16)", loadAccumulatorFromDirectWord],
  0xfb: ["EI", enableInterrupts],
  0xfe: ["CP d8", compareImmediate],
  0xff: ["RST 38H", (s) => restartFunction(s, 0x38)],
};

export function getNextInstruction(ctx: CpuState) {
  const opcode = fetchImmediateByte(ctx);

  if (opcode == 0xcb) {
    return getNextPrefixCbInstruction(ctx);
  }

  const instruction = instructions[opcode];

  if (typeof instruction === "undefined") {
    throw new Error(`Invalid opcode ${opcode.toString(16)}`);
  }

  return instruction;
}
