import { Register } from "../regs";

import {
  resetBitIndirectHL,
  resetBitRegister,
  rotateLeftCircularIndirectHL,
  rotateLeftCircularRegister,
  rotateLeftIndirectHL,
  rotateLeftRegister,
  rotateRightCircularIndirectHL,
  rotateRightCircularRegister,
  rotateRightIndirectHL,
  rotateRightRegister,
  setBitIndirectHL,
  setBitRegister,
  shiftLeftArithmeticIndirectHL,
  shiftLeftArithmeticRegister,
  shiftRightArithmeticIndirectHL,
  shiftRightArithmeticRegister,
  shiftRightLogicalIndirectHL,
  shiftRightLogicalRegister,
  swapNibblesIndirectHL,
  swapNibblesRegister,
  testBitIndirectHL,
  testBitRegister,
} from "./bitwise";
import { bindArgs, OpTable } from "./lib";

const prefixCBInstructions: OpTable = {
  0x00: ["RLC B", bindArgs(rotateLeftCircularRegister, Register.B)],
  0x01: ["RLC C", bindArgs(rotateLeftCircularRegister, Register.C)],
  0x02: ["RLC D", bindArgs(rotateLeftCircularRegister, Register.D)],
  0x03: ["RLC E", bindArgs(rotateLeftCircularRegister, Register.E)],
  0x04: ["RLC H", bindArgs(rotateLeftCircularRegister, Register.H)],
  0x05: ["RLC L", bindArgs(rotateLeftCircularRegister, Register.L)],
  0x06: ["RLC (HL)", rotateLeftCircularIndirectHL],
  0x07: ["RLC A", bindArgs(rotateLeftCircularRegister, Register.A)],
  0x08: ["RRC B", bindArgs(rotateRightCircularRegister, Register.B)],
  0x09: ["RRC C", bindArgs(rotateRightCircularRegister, Register.C)],
  0x0a: ["RRC D", bindArgs(rotateRightCircularRegister, Register.D)],
  0x0b: ["RRC E", bindArgs(rotateRightCircularRegister, Register.E)],
  0x0c: ["RRC H", bindArgs(rotateRightCircularRegister, Register.H)],
  0x0d: ["RRC L", bindArgs(rotateRightCircularRegister, Register.L)],
  0x0e: ["RRC (HL)", rotateRightCircularIndirectHL],
  0x0f: ["RRC A", bindArgs(rotateRightCircularRegister, Register.A)],

  0x10: ["RL B", bindArgs(rotateLeftRegister, Register.B)],
  0x11: ["RL C", bindArgs(rotateLeftRegister, Register.C)],
  0x12: ["RL D", bindArgs(rotateLeftRegister, Register.D)],
  0x13: ["RL E", bindArgs(rotateLeftRegister, Register.E)],
  0x14: ["RL H", bindArgs(rotateLeftRegister, Register.H)],
  0x15: ["RL L", bindArgs(rotateLeftRegister, Register.L)],
  0x16: ["RL (HL)", rotateLeftIndirectHL],
  0x17: ["RL A", bindArgs(rotateLeftRegister, Register.A)],
  0x18: ["RR B", bindArgs(rotateRightRegister, Register.B)],
  0x19: ["RR C", bindArgs(rotateRightRegister, Register.C)],
  0x1a: ["RR D", bindArgs(rotateRightRegister, Register.D)],
  0x1b: ["RR E", bindArgs(rotateRightRegister, Register.E)],
  0x1c: ["RR H", bindArgs(rotateRightRegister, Register.H)],
  0x1d: ["RR L", bindArgs(rotateRightRegister, Register.L)],
  0x1e: ["RR (HL)", rotateRightIndirectHL],
  0x1f: ["RR A", bindArgs(rotateRightRegister, Register.A)],

  0x20: ["SLA B", bindArgs(shiftLeftArithmeticRegister, Register.B)],
  0x21: ["SLA C", bindArgs(shiftLeftArithmeticRegister, Register.C)],
  0x22: ["SLA D", bindArgs(shiftLeftArithmeticRegister, Register.D)],
  0x23: ["SLA E", bindArgs(shiftLeftArithmeticRegister, Register.E)],
  0x24: ["SLA H", bindArgs(shiftLeftArithmeticRegister, Register.H)],
  0x25: ["SLA L", bindArgs(shiftLeftArithmeticRegister, Register.L)],
  0x26: ["SLA (HL)", shiftLeftArithmeticIndirectHL],
  0x27: ["SLA A", bindArgs(shiftLeftArithmeticRegister, Register.A)],
  0x28: ["SRA B", bindArgs(shiftRightArithmeticRegister, Register.B)],
  0x29: ["SRA C", bindArgs(shiftRightArithmeticRegister, Register.C)],
  0x2a: ["SRA D", bindArgs(shiftRightArithmeticRegister, Register.D)],
  0x2b: ["SRA E", bindArgs(shiftRightArithmeticRegister, Register.E)],
  0x2c: ["SRA H", bindArgs(shiftRightArithmeticRegister, Register.H)],
  0x2d: ["SRA L", bindArgs(shiftRightArithmeticRegister, Register.L)],
  0x2e: ["SRA (HL)", shiftRightArithmeticIndirectHL],
  0x2f: ["SRA A", bindArgs(shiftRightArithmeticRegister, Register.A)],

  0x30: ["SWAP B", bindArgs(swapNibblesRegister, Register.B)],
  0x31: ["SWAP C", bindArgs(swapNibblesRegister, Register.C)],
  0x32: ["SWAP D", bindArgs(swapNibblesRegister, Register.D)],
  0x33: ["SWAP E", bindArgs(swapNibblesRegister, Register.E)],
  0x34: ["SWAP H", bindArgs(swapNibblesRegister, Register.H)],
  0x35: ["SWAP L", bindArgs(swapNibblesRegister, Register.L)],
  0x36: ["SWAP (HL)", swapNibblesIndirectHL],
  0x37: ["SWAP A", bindArgs(swapNibblesRegister, Register.A)],
  0x38: ["SRL B", bindArgs(shiftRightLogicalRegister, Register.B)],
  0x39: ["SRL C", bindArgs(shiftRightLogicalRegister, Register.C)],
  0x3a: ["SRL D", bindArgs(shiftRightLogicalRegister, Register.D)],
  0x3b: ["SRL E", bindArgs(shiftRightLogicalRegister, Register.E)],
  0x3c: ["SRL H", bindArgs(shiftRightLogicalRegister, Register.H)],
  0x3d: ["SRL L", bindArgs(shiftRightLogicalRegister, Register.L)],
  0x3e: ["SRL (HL)", shiftRightLogicalIndirectHL],
  0x3f: ["SRL A", bindArgs(shiftRightLogicalRegister, Register.A)],

  0x40: ["BIT 0,B", bindArgs(testBitRegister, 0, Register.B)],
  0x41: ["BIT 0,C", bindArgs(testBitRegister, 0, Register.C)],
  0x42: ["BIT 0,D", bindArgs(testBitRegister, 0, Register.D)],
  0x43: ["BIT 0,E", bindArgs(testBitRegister, 0, Register.E)],
  0x44: ["BIT 0,H", bindArgs(testBitRegister, 0, Register.H)],
  0x45: ["BIT 0,L", bindArgs(testBitRegister, 0, Register.L)],
  0x46: ["BIT 0,(HL)", bindArgs(testBitIndirectHL, 0)],
  0x47: ["BIT 0,A", bindArgs(testBitRegister, 0, Register.A)],
  0x48: ["BIT 1,B", bindArgs(testBitRegister, 1, Register.B)],
  0x49: ["BIT 1,C", bindArgs(testBitRegister, 1, Register.C)],
  0x4a: ["BIT 1,D", bindArgs(testBitRegister, 1, Register.D)],
  0x4b: ["BIT 1,E", bindArgs(testBitRegister, 1, Register.E)],
  0x4c: ["BIT 1,H", bindArgs(testBitRegister, 1, Register.H)],
  0x4d: ["BIT 1,L", bindArgs(testBitRegister, 1, Register.L)],
  0x4e: ["BIT 1,(HL)", bindArgs(testBitIndirectHL, 1)],
  0x4f: ["BIT 1,A", bindArgs(testBitRegister, 1, Register.A)],

  0x50: ["BIT 2,B", bindArgs(testBitRegister, 2, Register.B)],
  0x51: ["BIT 2,C", bindArgs(testBitRegister, 2, Register.C)],
  0x52: ["BIT 2,D", bindArgs(testBitRegister, 2, Register.D)],
  0x53: ["BIT 2,E", bindArgs(testBitRegister, 2, Register.E)],
  0x54: ["BIT 2,H", bindArgs(testBitRegister, 2, Register.H)],
  0x55: ["BIT 2,L", bindArgs(testBitRegister, 2, Register.L)],
  0x56: ["BIT 2,(HL)", bindArgs(testBitIndirectHL, 2)],
  0x57: ["BIT 2,A", bindArgs(testBitRegister, 2, Register.A)],
  0x58: ["BIT 3,B", bindArgs(testBitRegister, 3, Register.B)],
  0x59: ["BIT 3,C", bindArgs(testBitRegister, 3, Register.C)],
  0x5a: ["BIT 3,D", bindArgs(testBitRegister, 3, Register.D)],
  0x5b: ["BIT 3,E", bindArgs(testBitRegister, 3, Register.E)],
  0x5c: ["BIT 3,H", bindArgs(testBitRegister, 3, Register.H)],
  0x5d: ["BIT 3,L", bindArgs(testBitRegister, 3, Register.L)],
  0x5e: ["BIT 3,(HL)", bindArgs(testBitIndirectHL, 3)],
  0x5f: ["BIT 3,A", bindArgs(testBitRegister, 3, Register.A)],

  0x60: ["BIT 4,B", bindArgs(testBitRegister, 4, Register.B)],
  0x61: ["BIT 4,C", bindArgs(testBitRegister, 4, Register.C)],
  0x62: ["BIT 4,D", bindArgs(testBitRegister, 4, Register.D)],
  0x63: ["BIT 4,E", bindArgs(testBitRegister, 4, Register.E)],
  0x64: ["BIT 4,H", bindArgs(testBitRegister, 4, Register.H)],
  0x65: ["BIT 4,L", bindArgs(testBitRegister, 4, Register.L)],
  0x66: ["BIT 4,(HL)", bindArgs(testBitIndirectHL, 4)],
  0x67: ["BIT 4,A", bindArgs(testBitRegister, 4, Register.A)],
  0x68: ["BIT 5,B", bindArgs(testBitRegister, 5, Register.B)],
  0x69: ["BIT 5,C", bindArgs(testBitRegister, 5, Register.C)],
  0x6a: ["BIT 5,D", bindArgs(testBitRegister, 5, Register.D)],
  0x6b: ["BIT 5,E", bindArgs(testBitRegister, 5, Register.E)],
  0x6c: ["BIT 5,H", bindArgs(testBitRegister, 5, Register.H)],
  0x6d: ["BIT 5,L", bindArgs(testBitRegister, 5, Register.L)],
  0x6e: ["BIT 5,(HL)", bindArgs(testBitIndirectHL, 5)],
  0x6f: ["BIT 5,A", bindArgs(testBitRegister, 5, Register.A)],

  0x70: ["BIT 6,B", bindArgs(testBitRegister, 6, Register.B)],
  0x71: ["BIT 6,C", bindArgs(testBitRegister, 6, Register.C)],
  0x72: ["BIT 6,D", bindArgs(testBitRegister, 6, Register.D)],
  0x73: ["BIT 6,E", bindArgs(testBitRegister, 6, Register.E)],
  0x74: ["BIT 6,H", bindArgs(testBitRegister, 6, Register.H)],
  0x75: ["BIT 6,L", bindArgs(testBitRegister, 6, Register.L)],
  0x76: ["BIT 6,(HL)", bindArgs(testBitIndirectHL, 6)],
  0x77: ["BIT 6,A", bindArgs(testBitRegister, 6, Register.A)],
  0x78: ["BIT 7,B", bindArgs(testBitRegister, 7, Register.B)],
  0x79: ["BIT 7,C", bindArgs(testBitRegister, 7, Register.C)],
  0x7a: ["BIT 7,D", bindArgs(testBitRegister, 7, Register.D)],
  0x7b: ["BIT 7,E", bindArgs(testBitRegister, 7, Register.E)],
  0x7c: ["BIT 7,H", bindArgs(testBitRegister, 7, Register.H)],
  0x7d: ["BIT 7,L", bindArgs(testBitRegister, 7, Register.L)],
  0x7e: ["BIT 7,(HL)", bindArgs(testBitIndirectHL, 7)],
  0x7f: ["BIT 7,A", bindArgs(testBitRegister, 7, Register.A)],

  0x80: ["RES 0,B", bindArgs(resetBitRegister, 0, Register.B)],
  0x81: ["RES 0,C", bindArgs(resetBitRegister, 0, Register.C)],
  0x82: ["RES 0,D", bindArgs(resetBitRegister, 0, Register.D)],
  0x83: ["RES 0,E", bindArgs(resetBitRegister, 0, Register.E)],
  0x84: ["RES 0,H", bindArgs(resetBitRegister, 0, Register.H)],
  0x85: ["RES 0,L", bindArgs(resetBitRegister, 0, Register.L)],
  0x86: ["RES 0,(HL)", bindArgs(resetBitIndirectHL, 0)],
  0x87: ["RES 0,A", bindArgs(resetBitRegister, 0, Register.A)],
  0x88: ["RES 1,B", bindArgs(resetBitRegister, 1, Register.B)],
  0x89: ["RES 1,C", bindArgs(resetBitRegister, 1, Register.C)],
  0x8a: ["RES 1,D", bindArgs(resetBitRegister, 1, Register.D)],
  0x8b: ["RES 1,E", bindArgs(resetBitRegister, 1, Register.E)],
  0x8c: ["RES 1,H", bindArgs(resetBitRegister, 1, Register.H)],
  0x8d: ["RES 1,L", bindArgs(resetBitRegister, 1, Register.L)],
  0x8e: ["RES 1,(HL)", bindArgs(resetBitIndirectHL, 1)],
  0x8f: ["RES 1,A", bindArgs(resetBitRegister, 1, Register.A)],

  0x90: ["RES 2,B", bindArgs(resetBitRegister, 2, Register.B)],
  0x91: ["RES 2,C", bindArgs(resetBitRegister, 2, Register.C)],
  0x92: ["RES 2,D", bindArgs(resetBitRegister, 2, Register.D)],
  0x93: ["RES 2,E", bindArgs(resetBitRegister, 2, Register.E)],
  0x94: ["RES 2,H", bindArgs(resetBitRegister, 2, Register.H)],
  0x95: ["RES 2,L", bindArgs(resetBitRegister, 2, Register.L)],
  0x96: ["RES 2,(HL)", bindArgs(resetBitIndirectHL, 2)],
  0x97: ["RES 2,A", bindArgs(resetBitRegister, 2, Register.A)],
  0x98: ["RES 3,B", bindArgs(resetBitRegister, 3, Register.B)],
  0x99: ["RES 3,C", bindArgs(resetBitRegister, 3, Register.C)],
  0x9a: ["RES 3,D", bindArgs(resetBitRegister, 3, Register.D)],
  0x9b: ["RES 3,E", bindArgs(resetBitRegister, 3, Register.E)],
  0x9c: ["RES 3,H", bindArgs(resetBitRegister, 3, Register.H)],
  0x9d: ["RES 3,L", bindArgs(resetBitRegister, 3, Register.L)],
  0x9e: ["RES 3,(HL)", bindArgs(resetBitIndirectHL, 3)],
  0x9f: ["RES 3,A", bindArgs(resetBitRegister, 3, Register.A)],

  0xa0: ["RES 4,B", bindArgs(resetBitRegister, 4, Register.B)],
  0xa1: ["RES 4,C", bindArgs(resetBitRegister, 4, Register.C)],
  0xa2: ["RES 4,D", bindArgs(resetBitRegister, 4, Register.D)],
  0xa3: ["RES 4,E", bindArgs(resetBitRegister, 4, Register.E)],
  0xa4: ["RES 4,H", bindArgs(resetBitRegister, 4, Register.H)],
  0xa5: ["RES 4,L", bindArgs(resetBitRegister, 4, Register.L)],
  0xa6: ["RES 4,(HL)", bindArgs(resetBitIndirectHL, 4)],
  0xa7: ["RES 4,A", bindArgs(resetBitRegister, 4, Register.A)],
  0xa8: ["RES 5,B", bindArgs(resetBitRegister, 5, Register.B)],
  0xa9: ["RES 5,C", bindArgs(resetBitRegister, 5, Register.C)],
  0xaa: ["RES 5,D", bindArgs(resetBitRegister, 5, Register.D)],
  0xab: ["RES 5,E", bindArgs(resetBitRegister, 5, Register.E)],
  0xac: ["RES 5,H", bindArgs(resetBitRegister, 5, Register.H)],
  0xad: ["RES 5,L", bindArgs(resetBitRegister, 5, Register.L)],
  0xae: ["RES 5,(HL)", bindArgs(resetBitIndirectHL, 5)],
  0xaf: ["RES 5,A", bindArgs(resetBitRegister, 5, Register.A)],

  0xb0: ["RES 6,B", bindArgs(resetBitRegister, 6, Register.B)],
  0xb1: ["RES 6,C", bindArgs(resetBitRegister, 6, Register.C)],
  0xb2: ["RES 6,D", bindArgs(resetBitRegister, 6, Register.D)],
  0xb3: ["RES 6,E", bindArgs(resetBitRegister, 6, Register.E)],
  0xb4: ["RES 6,H", bindArgs(resetBitRegister, 6, Register.H)],
  0xb5: ["RES 6,L", bindArgs(resetBitRegister, 6, Register.L)],
  0xb6: ["RES 6,(HL)", bindArgs(resetBitIndirectHL, 6)],
  0xb7: ["RES 6,A", bindArgs(resetBitRegister, 6, Register.A)],
  0xb8: ["RES 7,B", bindArgs(resetBitRegister, 7, Register.B)],
  0xb9: ["RES 7,C", bindArgs(resetBitRegister, 7, Register.C)],
  0xba: ["RES 7,D", bindArgs(resetBitRegister, 7, Register.D)],
  0xbb: ["RES 7,E", bindArgs(resetBitRegister, 7, Register.E)],
  0xbc: ["RES 7,H", bindArgs(resetBitRegister, 7, Register.H)],
  0xbd: ["RES 7,L", bindArgs(resetBitRegister, 7, Register.L)],
  0xbe: ["RES 7,(HL)", bindArgs(resetBitIndirectHL, 7)],
  0xbf: ["RES 7,A", bindArgs(resetBitRegister, 7, Register.A)],

  0xc0: ["SET 0,B", bindArgs(setBitRegister, 0, Register.B)],
  0xc1: ["SET 0,C", bindArgs(setBitRegister, 0, Register.C)],
  0xc2: ["SET 0,D", bindArgs(setBitRegister, 0, Register.D)],
  0xc3: ["SET 0,E", bindArgs(setBitRegister, 0, Register.E)],
  0xc4: ["SET 0,H", bindArgs(setBitRegister, 0, Register.H)],
  0xc5: ["SET 0,L", bindArgs(setBitRegister, 0, Register.L)],
  0xc6: ["SET 0,(HL)", bindArgs(setBitIndirectHL, 0)],
  0xc7: ["SET 0,A", bindArgs(setBitRegister, 0, Register.A)],
  0xc8: ["SET 1,B", bindArgs(setBitRegister, 1, Register.B)],
  0xc9: ["SET 1,C", bindArgs(setBitRegister, 1, Register.C)],
  0xca: ["SET 1,D", bindArgs(setBitRegister, 1, Register.D)],
  0xcb: ["SET 1,E", bindArgs(setBitRegister, 1, Register.E)],
  0xcc: ["SET 1,H", bindArgs(setBitRegister, 1, Register.H)],
  0xcd: ["SET 1,L", bindArgs(setBitRegister, 1, Register.L)],
  0xce: ["SET 1,(HL)", bindArgs(setBitIndirectHL, 1)],
  0xcf: ["SET 1,A", bindArgs(setBitRegister, 1, Register.A)],

  0xd0: ["SET 2,B", bindArgs(setBitRegister, 2, Register.B)],
  0xd1: ["SET 2,C", bindArgs(setBitRegister, 2, Register.C)],
  0xd2: ["SET 2,D", bindArgs(setBitRegister, 2, Register.D)],
  0xd3: ["SET 2,E", bindArgs(setBitRegister, 2, Register.E)],
  0xd4: ["SET 2,H", bindArgs(setBitRegister, 2, Register.H)],
  0xd5: ["SET 2,L", bindArgs(setBitRegister, 2, Register.L)],
  0xd6: ["SET 2,(HL)", bindArgs(setBitIndirectHL, 2)],
  0xd7: ["SET 2,A", bindArgs(setBitRegister, 2, Register.A)],
  0xd8: ["SET 3,B", bindArgs(setBitRegister, 3, Register.B)],
  0xd9: ["SET 3,C", bindArgs(setBitRegister, 3, Register.C)],
  0xda: ["SET 3,D", bindArgs(setBitRegister, 3, Register.D)],
  0xdb: ["SET 3,E", bindArgs(setBitRegister, 3, Register.E)],
  0xdc: ["SET 3,H", bindArgs(setBitRegister, 3, Register.H)],
  0xdd: ["SET 3,L", bindArgs(setBitRegister, 3, Register.L)],
  0xde: ["SET 3,(HL)", bindArgs(setBitIndirectHL, 3)],
  0xdf: ["SET 3,A", bindArgs(setBitRegister, 3, Register.A)],

  0xe0: ["SET 4,B", bindArgs(setBitRegister, 4, Register.B)],
  0xe1: ["SET 4,C", bindArgs(setBitRegister, 4, Register.C)],
  0xe2: ["SET 4,D", bindArgs(setBitRegister, 4, Register.D)],
  0xe3: ["SET 4,E", bindArgs(setBitRegister, 4, Register.E)],
  0xe4: ["SET 4,H", bindArgs(setBitRegister, 4, Register.H)],
  0xe5: ["SET 4,L", bindArgs(setBitRegister, 4, Register.L)],
  0xe6: ["SET 4,(HL)", bindArgs(setBitIndirectHL, 4)],
  0xe7: ["SET 4,A", bindArgs(setBitRegister, 4, Register.A)],
  0xe8: ["SET 5,B", bindArgs(setBitRegister, 5, Register.B)],
  0xe9: ["SET 5,C", bindArgs(setBitRegister, 5, Register.C)],
  0xea: ["SET 5,D", bindArgs(setBitRegister, 5, Register.D)],
  0xeb: ["SET 5,E", bindArgs(setBitRegister, 5, Register.E)],
  0xec: ["SET 5,H", bindArgs(setBitRegister, 5, Register.H)],
  0xed: ["SET 5,L", bindArgs(setBitRegister, 5, Register.L)],
  0xee: ["SET 5,(HL)", bindArgs(setBitIndirectHL, 5)],
  0xef: ["SET 5,A", bindArgs(setBitRegister, 5, Register.A)],

  0xf0: ["SET 6,B", bindArgs(setBitRegister, 6, Register.B)],
  0xf1: ["SET 6,C", bindArgs(setBitRegister, 6, Register.C)],
  0xf2: ["SET 6,D", bindArgs(setBitRegister, 6, Register.D)],
  0xf3: ["SET 6,E", bindArgs(setBitRegister, 6, Register.E)],
  0xf4: ["SET 6,H", bindArgs(setBitRegister, 6, Register.H)],
  0xf5: ["SET 6,L", bindArgs(setBitRegister, 6, Register.L)],
  0xf6: ["SET 6,(HL)", bindArgs(setBitIndirectHL, 6)],
  0xf7: ["SET 6,A", bindArgs(setBitRegister, 6, Register.A)],
  0xf8: ["SET 7,B", bindArgs(setBitRegister, 7, Register.B)],
  0xf9: ["SET 7,C", bindArgs(setBitRegister, 7, Register.C)],
  0xfa: ["SET 7,D", bindArgs(setBitRegister, 7, Register.D)],
  0xfb: ["SET 7,E", bindArgs(setBitRegister, 7, Register.E)],
  0xfc: ["SET 7,H", bindArgs(setBitRegister, 7, Register.H)],
  0xfd: ["SET 7,L", bindArgs(setBitRegister, 7, Register.L)],
  0xfe: ["SET 7,(HL)", bindArgs(setBitIndirectHL, 7)],
  0xff: ["SET 7,A", bindArgs(setBitRegister, 7, Register.A)],
};

export function getPrefixCBInstruction(opcode: number) {
  return prefixCBInstructions[opcode];
}
