import { CpuState, fetchImmediateByte } from "../cpu-state";
import { Register } from "../regs";

import {
  resetBitIndirectHL,
  resetBitRegister,
  rotateLeftCircularIndirectHL,
  rotateLeftCircularRegister,
  rotateLeftIndirectHL,
  rotateLeftRegister,
  rotateRightCircularIndirectHL,
  rotateRightCircularRegister,
  rotateRightIndirectHL,
  rotateRightRegister,
  setBitIndirectHL,
  setBitRegister,
  shiftLeftArithmeticIndirectHL,
  shiftLeftArithmeticRegister,
  shiftRightArithmeticIndirectHL,
  shiftRightArithmeticRegister,
  shiftRightLogicalIndirectHL,
  shiftRightLogicalRegister,
  swapNibblesIndirectHL,
  swapNibblesRegister,
  testBitIndirectHL,
  testBitRegister,
} from "./bitwise";
import { OpTable } from "./lib";

const prefixCBInstructions: OpTable = {
  0x00: ["RLC B", (s) => rotateLeftCircularRegister(s, Register.B)],
  0x01: ["RLC C", (s) => rotateLeftCircularRegister(s, Register.C)],
  0x02: ["RLC D", (s) => rotateLeftCircularRegister(s, Register.D)],
  0x03: ["RLC E", (s) => rotateLeftCircularRegister(s, Register.E)],
  0x04: ["RLC H", (s) => rotateLeftCircularRegister(s, Register.H)],
  0x05: ["RLC L", (s) => rotateLeftCircularRegister(s, Register.L)],
  0x06: ["RLC (HL)", rotateLeftCircularIndirectHL],
  0x07: ["RLC A", (s) => rotateLeftCircularRegister(s, Register.A)],
  0x08: ["RRC B", (s) => rotateRightCircularRegister(s, Register.B)],
  0x09: ["RRC C", (s) => rotateRightCircularRegister(s, Register.C)],
  0x0a: ["RRC D", (s) => rotateRightCircularRegister(s, Register.D)],
  0x0b: ["RRC E", (s) => rotateRightCircularRegister(s, Register.E)],
  0x0c: ["RRC H", (s) => rotateRightCircularRegister(s, Register.H)],
  0x0d: ["RRC L", (s) => rotateRightCircularRegister(s, Register.L)],
  0x0e: ["RRC (HL)", rotateRightCircularIndirectHL],
  0x0f: ["RRC A", (s) => rotateRightCircularRegister(s, Register.A)],

  0x10: ["RL B", (s) => rotateLeftRegister(s, Register.B)],
  0x11: ["RL C", (s) => rotateLeftRegister(s, Register.C)],
  0x12: ["RL D", (s) => rotateLeftRegister(s, Register.D)],
  0x13: ["RL E", (s) => rotateLeftRegister(s, Register.E)],
  0x14: ["RL H", (s) => rotateLeftRegister(s, Register.H)],
  0x15: ["RL L", (s) => rotateLeftRegister(s, Register.L)],
  0x16: ["RL (HL)", rotateLeftIndirectHL],
  0x17: ["RL A", (s) => rotateLeftRegister(s, Register.A)],
  0x18: ["RR B", (s) => rotateRightRegister(s, Register.B)],
  0x19: ["RR C", (s) => rotateRightRegister(s, Register.C)],
  0x1a: ["RR D", (s) => rotateRightRegister(s, Register.D)],
  0x1b: ["RR E", (s) => rotateRightRegister(s, Register.E)],
  0x1c: ["RR H", (s) => rotateRightRegister(s, Register.H)],
  0x1d: ["RR L", (s) => rotateRightRegister(s, Register.L)],
  0x1e: ["RR (HL)", rotateRightIndirectHL],
  0x1f: ["RR A", (s) => rotateRightRegister(s, Register.A)],

  0x20: ["SLA B", (s) => shiftLeftArithmeticRegister(s, Register.B)],
  0x21: ["SLA C", (s) => shiftLeftArithmeticRegister(s, Register.C)],
  0x22: ["SLA D", (s) => shiftLeftArithmeticRegister(s, Register.D)],
  0x23: ["SLA E", (s) => shiftLeftArithmeticRegister(s, Register.E)],
  0x24: ["SLA H", (s) => shiftLeftArithmeticRegister(s, Register.H)],
  0x25: ["SLA L", (s) => shiftLeftArithmeticRegister(s, Register.L)],
  0x26: ["SLA (HL)", shiftLeftArithmeticIndirectHL],
  0x27: ["SLA A", (s) => shiftLeftArithmeticRegister(s, Register.A)],
  0x28: ["SRA B", (s) => shiftRightArithmeticRegister(s, Register.B)],
  0x29: ["SRA C", (s) => shiftRightArithmeticRegister(s, Register.C)],
  0x2a: ["SRA D", (s) => shiftRightArithmeticRegister(s, Register.D)],
  0x2b: ["SRA E", (s) => shiftRightArithmeticRegister(s, Register.E)],
  0x2c: ["SRA H", (s) => shiftRightArithmeticRegister(s, Register.H)],
  0x2d: ["SRA L", (s) => shiftRightArithmeticRegister(s, Register.L)],
  0x2e: ["SRA (HL)", shiftRightArithmeticIndirectHL],
  0x2f: ["SRA A", (s) => shiftRightArithmeticRegister(s, Register.A)],

  0x30: ["SWAP B", (s) => swapNibblesRegister(s, Register.B)],
  0x31: ["SWAP C", (s) => swapNibblesRegister(s, Register.C)],
  0x32: ["SWAP D", (s) => swapNibblesRegister(s, Register.D)],
  0x33: ["SWAP E", (s) => swapNibblesRegister(s, Register.E)],
  0x34: ["SWAP H", (s) => swapNibblesRegister(s, Register.H)],
  0x35: ["SWAP L", (s) => swapNibblesRegister(s, Register.L)],
  0x36: ["SWAP (HL)", swapNibblesIndirectHL],
  0x37: ["SWAP A", (s) => swapNibblesRegister(s, Register.A)],
  0x38: ["SRL B", (s) => shiftRightLogicalRegister(s, Register.B)],
  0x39: ["SRL C", (s) => shiftRightLogicalRegister(s, Register.C)],
  0x3a: ["SRL D", (s) => shiftRightLogicalRegister(s, Register.D)],
  0x3b: ["SRL E", (s) => shiftRightLogicalRegister(s, Register.E)],
  0x3c: ["SRL H", (s) => shiftRightLogicalRegister(s, Register.H)],
  0x3d: ["SRL L", (s) => shiftRightLogicalRegister(s, Register.L)],
  0x3e: ["SRL (HL)", shiftRightLogicalIndirectHL],
  0x3f: ["SRL A", (s) => shiftRightLogicalRegister(s, Register.A)],

  0x40: ["BIT 0,B", (s) => testBitRegister(s, 0, Register.B)],
  0x41: ["BIT 0,C", (s) => testBitRegister(s, 0, Register.C)],
  0x42: ["BIT 0,D", (s) => testBitRegister(s, 0, Register.D)],
  0x43: ["BIT 0,E", (s) => testBitRegister(s, 0, Register.E)],
  0x44: ["BIT 0,H", (s) => testBitRegister(s, 0, Register.H)],
  0x45: ["BIT 0,L", (s) => testBitRegister(s, 0, Register.L)],
  0x46: ["BIT 0,(HL)", (s) => testBitIndirectHL(s, 0)],
  0x47: ["BIT 0,A", (s) => testBitRegister(s, 0, Register.A)],
  0x48: ["BIT 1,B", (s) => testBitRegister(s, 1, Register.B)],
  0x49: ["BIT 1,C", (s) => testBitRegister(s, 1, Register.C)],
  0x4a: ["BIT 1,D", (s) => testBitRegister(s, 1, Register.D)],
  0x4b: ["BIT 1,E", (s) => testBitRegister(s, 1, Register.E)],
  0x4c: ["BIT 1,H", (s) => testBitRegister(s, 1, Register.H)],
  0x4d: ["BIT 1,L", (s) => testBitRegister(s, 1, Register.L)],
  0x4e: ["BIT 1,(HL)", (s) => testBitIndirectHL(s, 1)],
  0x4f: ["BIT 1,A", (s) => testBitRegister(s, 1, Register.A)],

  0x50: ["BIT 2,B", (s) => testBitRegister(s, 2, Register.B)],
  0x51: ["BIT 2,C", (s) => testBitRegister(s, 2, Register.C)],
  0x52: ["BIT 2,D", (s) => testBitRegister(s, 2, Register.D)],
  0x53: ["BIT 2,E", (s) => testBitRegister(s, 2, Register.E)],
  0x54: ["BIT 2,H", (s) => testBitRegister(s, 2, Register.H)],
  0x55: ["BIT 2,L", (s) => testBitRegister(s, 2, Register.L)],
  0x56: ["BIT 2,(HL)", (s) => testBitIndirectHL(s, 2)],
  0x57: ["BIT 2,A", (s) => testBitRegister(s, 2, Register.A)],
  0x58: ["BIT 3,B", (s) => testBitRegister(s, 3, Register.B)],
  0x59: ["BIT 3,C", (s) => testBitRegister(s, 3, Register.C)],
  0x5a: ["BIT 3,D", (s) => testBitRegister(s, 3, Register.D)],
  0x5b: ["BIT 3,E", (s) => testBitRegister(s, 3, Register.E)],
  0x5c: ["BIT 3,H", (s) => testBitRegister(s, 3, Register.H)],
  0x5d: ["BIT 3,L", (s) => testBitRegister(s, 3, Register.L)],
  0x5e: ["BIT 3,(HL)", (s) => testBitIndirectHL(s, 3)],
  0x5f: ["BIT 3,A", (s) => testBitRegister(s, 3, Register.A)],

  0x60: ["BIT 4,B", (s) => testBitRegister(s, 4, Register.B)],
  0x61: ["BIT 4,C", (s) => testBitRegister(s, 4, Register.C)],
  0x62: ["BIT 4,D", (s) => testBitRegister(s, 4, Register.D)],
  0x63: ["BIT 4,E", (s) => testBitRegister(s, 4, Register.E)],
  0x64: ["BIT 4,H", (s) => testBitRegister(s, 4, Register.H)],
  0x65: ["BIT 4,L", (s) => testBitRegister(s, 4, Register.L)],
  0x66: ["BIT 4,(HL)", (s) => testBitIndirectHL(s, 4)],
  0x67: ["BIT 4,A", (s) => testBitRegister(s, 4, Register.A)],
  0x68: ["BIT 5,B", (s) => testBitRegister(s, 5, Register.B)],
  0x69: ["BIT 5,C", (s) => testBitRegister(s, 5, Register.C)],
  0x6a: ["BIT 5,D", (s) => testBitRegister(s, 5, Register.D)],
  0x6b: ["BIT 5,E", (s) => testBitRegister(s, 5, Register.E)],
  0x6c: ["BIT 5,H", (s) => testBitRegister(s, 5, Register.H)],
  0x6d: ["BIT 5,L", (s) => testBitRegister(s, 5, Register.L)],
  0x6e: ["BIT 5,(HL)", (s) => testBitIndirectHL(s, 5)],
  0x6f: ["BIT 5,A", (s) => testBitRegister(s, 5, Register.A)],

  0x70: ["BIT 6,B", (s) => testBitRegister(s, 6, Register.B)],
  0x71: ["BIT 6,C", (s) => testBitRegister(s, 6, Register.C)],
  0x72: ["BIT 6,D", (s) => testBitRegister(s, 6, Register.D)],
  0x73: ["BIT 6,E", (s) => testBitRegister(s, 6, Register.E)],
  0x74: ["BIT 6,H", (s) => testBitRegister(s, 6, Register.H)],
  0x75: ["BIT 6,L", (s) => testBitRegister(s, 6, Register.L)],
  0x76: ["BIT 6,(HL)", (s) => testBitIndirectHL(s, 6)],
  0x77: ["BIT 6,A", (s) => testBitRegister(s, 6, Register.A)],
  0x78: ["BIT 7,B", (s) => testBitRegister(s, 7, Register.B)],
  0x79: ["BIT 7,C", (s) => testBitRegister(s, 7, Register.C)],
  0x7a: ["BIT 7,D", (s) => testBitRegister(s, 7, Register.D)],
  0x7b: ["BIT 7,E", (s) => testBitRegister(s, 7, Register.E)],
  0x7c: ["BIT 7,H", (s) => testBitRegister(s, 7, Register.H)],
  0x7d: ["BIT 7,L", (s) => testBitRegister(s, 7, Register.L)],
  0x7e: ["BIT 7,(HL)", (s) => testBitIndirectHL(s, 7)],
  0x7f: ["BIT 7,A", (s) => testBitRegister(s, 7, Register.A)],

  0x80: ["RES 0,B", (s) => resetBitRegister(s, 0, Register.B)],
  0x81: ["RES 0,C", (s) => resetBitRegister(s, 0, Register.C)],
  0x82: ["RES 0,D", (s) => resetBitRegister(s, 0, Register.D)],
  0x83: ["RES 0,E", (s) => resetBitRegister(s, 0, Register.E)],
  0x84: ["RES 0,H", (s) => resetBitRegister(s, 0, Register.H)],
  0x85: ["RES 0,L", (s) => resetBitRegister(s, 0, Register.L)],
  0x86: ["RES 0,(HL)", (s) => resetBitIndirectHL(s, 0)],
  0x87: ["RES 0,A", (s) => resetBitRegister(s, 0, Register.A)],
  0x88: ["RES 1,B", (s) => resetBitRegister(s, 1, Register.B)],
  0x89: ["RES 1,C", (s) => resetBitRegister(s, 1, Register.C)],
  0x8a: ["RES 1,D", (s) => resetBitRegister(s, 1, Register.D)],
  0x8b: ["RES 1,E", (s) => resetBitRegister(s, 1, Register.E)],
  0x8c: ["RES 1,H", (s) => resetBitRegister(s, 1, Register.H)],
  0x8d: ["RES 1,L", (s) => resetBitRegister(s, 1, Register.L)],
  0x8e: ["RES 1,(HL)", (s) => resetBitIndirectHL(s, 1)],
  0x8f: ["RES 1,A", (s) => resetBitRegister(s, 1, Register.A)],

  0x90: ["RES 2,B", (s) => resetBitRegister(s, 2, Register.B)],
  0x91: ["RES 2,C", (s) => resetBitRegister(s, 2, Register.C)],
  0x92: ["RES 2,D", (s) => resetBitRegister(s, 2, Register.D)],
  0x93: ["RES 2,E", (s) => resetBitRegister(s, 2, Register.E)],
  0x94: ["RES 2,H", (s) => resetBitRegister(s, 2, Register.H)],
  0x95: ["RES 2,L", (s) => resetBitRegister(s, 2, Register.L)],
  0x96: ["RES 2,(HL)", (s) => resetBitIndirectHL(s, 2)],
  0x97: ["RES 2,A", (s) => resetBitRegister(s, 2, Register.A)],
  0x98: ["RES 3,B", (s) => resetBitRegister(s, 3, Register.B)],
  0x99: ["RES 3,C", (s) => resetBitRegister(s, 3, Register.C)],
  0x9a: ["RES 3,D", (s) => resetBitRegister(s, 3, Register.D)],
  0x9b: ["RES 3,E", (s) => resetBitRegister(s, 3, Register.E)],
  0x9c: ["RES 3,H", (s) => resetBitRegister(s, 3, Register.H)],
  0x9d: ["RES 3,L", (s) => resetBitRegister(s, 3, Register.L)],
  0x9e: ["RES 3,(HL)", (s) => resetBitIndirectHL(s, 3)],
  0x9f: ["RES 3,A", (s) => resetBitRegister(s, 3, Register.A)],

  0xa0: ["RES 4,B", (s) => resetBitRegister(s, 4, Register.B)],
  0xa1: ["RES 4,C", (s) => resetBitRegister(s, 4, Register.C)],
  0xa2: ["RES 4,D", (s) => resetBitRegister(s, 4, Register.D)],
  0xa3: ["RES 4,E", (s) => resetBitRegister(s, 4, Register.E)],
  0xa4: ["RES 4,H", (s) => resetBitRegister(s, 4, Register.H)],
  0xa5: ["RES 4,L", (s) => resetBitRegister(s, 4, Register.L)],
  0xa6: ["RES 4,(HL)", (s) => resetBitIndirectHL(s, 4)],
  0xa7: ["RES 4,A", (s) => resetBitRegister(s, 4, Register.A)],
  0xa8: ["RES 5,B", (s) => resetBitRegister(s, 5, Register.B)],
  0xa9: ["RES 5,C", (s) => resetBitRegister(s, 5, Register.C)],
  0xaa: ["RES 5,D", (s) => resetBitRegister(s, 5, Register.D)],
  0xab: ["RES 5,E", (s) => resetBitRegister(s, 5, Register.E)],
  0xac: ["RES 5,H", (s) => resetBitRegister(s, 5, Register.H)],
  0xad: ["RES 5,L", (s) => resetBitRegister(s, 5, Register.L)],
  0xae: ["RES 5,(HL)", (s) => resetBitIndirectHL(s, 5)],
  0xaf: ["RES 5,A", (s) => resetBitRegister(s, 5, Register.A)],

  0xb0: ["RES 6,B", (s) => resetBitRegister(s, 6, Register.B)],
  0xb1: ["RES 6,C", (s) => resetBitRegister(s, 6, Register.C)],
  0xb2: ["RES 6,D", (s) => resetBitRegister(s, 6, Register.D)],
  0xb3: ["RES 6,E", (s) => resetBitRegister(s, 6, Register.E)],
  0xb4: ["RES 6,H", (s) => resetBitRegister(s, 6, Register.H)],
  0xb5: ["RES 6,L", (s) => resetBitRegister(s, 6, Register.L)],
  0xb6: ["RES 6,(HL)", (s) => resetBitIndirectHL(s, 6)],
  0xb7: ["RES 6,A", (s) => resetBitRegister(s, 6, Register.A)],
  0xb8: ["RES 7,B", (s) => resetBitRegister(s, 7, Register.B)],
  0xb9: ["RES 7,C", (s) => resetBitRegister(s, 7, Register.C)],
  0xba: ["RES 7,D", (s) => resetBitRegister(s, 7, Register.D)],
  0xbb: ["RES 7,E", (s) => resetBitRegister(s, 7, Register.E)],
  0xbc: ["RES 7,H", (s) => resetBitRegister(s, 7, Register.H)],
  0xbd: ["RES 7,L", (s) => resetBitRegister(s, 7, Register.L)],
  0xbe: ["RES 7,(HL)", (s) => resetBitIndirectHL(s, 7)],
  0xbf: ["RES 7,A", (s) => resetBitRegister(s, 7, Register.A)],

  0xc0: ["SET 0,B", (s) => setBitRegister(s, 0, Register.B)],
  0xc1: ["SET 0,C", (s) => setBitRegister(s, 0, Register.C)],
  0xc2: ["SET 0,D", (s) => setBitRegister(s, 0, Register.D)],
  0xc3: ["SET 0,E", (s) => setBitRegister(s, 0, Register.E)],
  0xc4: ["SET 0,H", (s) => setBitRegister(s, 0, Register.H)],
  0xc5: ["SET 0,L", (s) => setBitRegister(s, 0, Register.L)],
  0xc6: ["SET 0,(HL)", (s) => setBitIndirectHL(s, 0)],
  0xc7: ["SET 0,A", (s) => setBitRegister(s, 0, Register.A)],
  0xc8: ["SET 1,B", (s) => setBitRegister(s, 1, Register.B)],
  0xc9: ["SET 1,C", (s) => setBitRegister(s, 1, Register.C)],
  0xca: ["SET 1,D", (s) => setBitRegister(s, 1, Register.D)],
  0xcb: ["SET 1,E", (s) => setBitRegister(s, 1, Register.E)],
  0xcc: ["SET 1,H", (s) => setBitRegister(s, 1, Register.H)],
  0xcd: ["SET 1,L", (s) => setBitRegister(s, 1, Register.L)],
  0xce: ["SET 1,(HL)", (s) => setBitIndirectHL(s, 1)],
  0xcf: ["SET 1,A", (s) => setBitRegister(s, 1, Register.A)],

  0xd0: ["SET 2,B", (s) => setBitRegister(s, 2, Register.B)],
  0xd1: ["SET 2,C", (s) => setBitRegister(s, 2, Register.C)],
  0xd2: ["SET 2,D", (s) => setBitRegister(s, 2, Register.D)],
  0xd3: ["SET 2,E", (s) => setBitRegister(s, 2, Register.E)],
  0xd4: ["SET 2,H", (s) => setBitRegister(s, 2, Register.H)],
  0xd5: ["SET 2,L", (s) => setBitRegister(s, 2, Register.L)],
  0xd6: ["SET 2,(HL)", (s) => setBitIndirectHL(s, 2)],
  0xd7: ["SET 2,A", (s) => setBitRegister(s, 2, Register.A)],
  0xd8: ["SET 3,B", (s) => setBitRegister(s, 3, Register.B)],
  0xd9: ["SET 3,C", (s) => setBitRegister(s, 3, Register.C)],
  0xda: ["SET 3,D", (s) => setBitRegister(s, 3, Register.D)],
  0xdb: ["SET 3,E", (s) => setBitRegister(s, 3, Register.E)],
  0xdc: ["SET 3,H", (s) => setBitRegister(s, 3, Register.H)],
  0xdd: ["SET 3,L", (s) => setBitRegister(s, 3, Register.L)],
  0xde: ["SET 3,(HL)", (s) => setBitIndirectHL(s, 3)],
  0xdf: ["SET 3,A", (s) => setBitRegister(s, 3, Register.A)],

  0xe0: ["SET 4,B", (s) => setBitRegister(s, 4, Register.B)],
  0xe1: ["SET 4,C", (s) => setBitRegister(s, 4, Register.C)],
  0xe2: ["SET 4,D", (s) => setBitRegister(s, 4, Register.D)],
  0xe3: ["SET 4,E", (s) => setBitRegister(s, 4, Register.E)],
  0xe4: ["SET 4,H", (s) => setBitRegister(s, 4, Register.H)],
  0xe5: ["SET 4,L", (s) => setBitRegister(s, 4, Register.L)],
  0xe6: ["SET 4,(HL)", (s) => setBitIndirectHL(s, 4)],
  0xe7: ["SET 4,A", (s) => setBitRegister(s, 4, Register.A)],
  0xe8: ["SET 5,B", (s) => setBitRegister(s, 5, Register.B)],
  0xe9: ["SET 5,C", (s) => setBitRegister(s, 5, Register.C)],
  0xea: ["SET 5,D", (s) => setBitRegister(s, 5, Register.D)],
  0xeb: ["SET 5,E", (s) => setBitRegister(s, 5, Register.E)],
  0xec: ["SET 5,H", (s) => setBitRegister(s, 5, Register.H)],
  0xed: ["SET 5,L", (s) => setBitRegister(s, 5, Register.L)],
  0xee: ["SET 5,(HL)", (s) => setBitIndirectHL(s, 5)],
  0xef: ["SET 5,A", (s) => setBitRegister(s, 5, Register.A)],

  0xf0: ["SET 6,B", (s) => setBitRegister(s, 6, Register.B)],
  0xf1: ["SET 6,C", (s) => setBitRegister(s, 6, Register.C)],
  0xf2: ["SET 6,D", (s) => setBitRegister(s, 6, Register.D)],
  0xf3: ["SET 6,E", (s) => setBitRegister(s, 6, Register.E)],
  0xf4: ["SET 6,H", (s) => setBitRegister(s, 6, Register.H)],
  0xf5: ["SET 6,L", (s) => setBitRegister(s, 6, Register.L)],
  0xf6: ["SET 6,(HL)", (s) => setBitIndirectHL(s, 6)],
  0xf7: ["SET 6,A", (s) => setBitRegister(s, 6, Register.A)],
  0xf8: ["SET 7,B", (s) => setBitRegister(s, 7, Register.B)],
  0xf9: ["SET 7,C", (s) => setBitRegister(s, 7, Register.C)],
  0xfa: ["SET 7,D", (s) => setBitRegister(s, 7, Register.D)],
  0xfb: ["SET 7,E", (s) => setBitRegister(s, 7, Register.E)],
  0xfc: ["SET 7,H", (s) => setBitRegister(s, 7, Register.H)],
  0xfd: ["SET 7,L", (s) => setBitRegister(s, 7, Register.L)],
  0xfe: ["SET 7,(HL)", (s) => setBitIndirectHL(s, 7)],
  0xff: ["SET 7,A", (s) => setBitRegister(s, 7, Register.A)],
};

export function getNextPrefixCbInstruction(state: CpuState) {
  const opcode = fetchImmediateByte(state);
  const instruction = prefixCBInstructions[opcode];

  if (typeof instruction === "undefined") {
    throw new Error(`Invalid opcode CB ${opcode.toString(16)}`);
  }

  return instruction;
}
